name: Update Docker Hub Description
on:
  push:
    branches:
    - master
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy README.md to TEST.md
        run: |
          mkdir -p some/path
          mv README.md some/path/TEST.md
      - name: Docker Hub Description
        uses: ./
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: peterevans/dockerhub-description
          README_FILEPATH: ./some/path/TEST.md
